[package]
name = "temperature_converter"
version = "0.1.0"
authors = ["Kristian Maglasang <kristian.g.maglasang@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
